// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-LUs5L7IYkDcVOyIXQvoGGgsE2vbxSpA',
    appId: '1:221524605439:web:5fe43534b026d880c9cfca',
    messagingSenderId: '221524605439',
    projectId: 'nofap-islam',
    authDomain: 'nofap-islam.firebaseapp.com',
    storageBucket: 'nofap-islam.firebasestorage.app',
    measurementId: 'G-82PLFR07BK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy_lLgTl1d17bxX07DfQFPYez0PygcDZQ',
    appId: '1:221524605439:android:e45d12664eb77b39c9cfca',
    messagingSenderId: '221524605439',
    projectId: 'nofap-islam',
    storageBucket: 'nofap-islam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYxAlz3VKtsltR_ZTAX8Fu3tm_A3Kf1uY',
    appId: '1:221524605439:ios:7fb746b33a6d50ecc9cfca',
    messagingSenderId: '221524605439',
    projectId: 'nofap-islam',
    storageBucket: 'nofap-islam.firebasestorage.app',
    iosBundleId: 'com.example.purityPath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYxAlz3VKtsltR_ZTAX8Fu3tm_A3Kf1uY',
    appId: '1:221524605439:ios:7fb746b33a6d50ecc9cfca',
    messagingSenderId: '221524605439',
    projectId: 'nofap-islam',
    storageBucket: 'nofap-islam.firebasestorage.app',
    iosBundleId: 'com.example.purityPath',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-LUs5L7IYkDcVOyIXQvoGGgsE2vbxSpA',
    appId: '1:221524605439:web:6eae19ca5f4a09bdc9cfca',
    messagingSenderId: '221524605439',
    projectId: 'nofap-islam',
    authDomain: 'nofap-islam.firebaseapp.com',
    storageBucket: 'nofap-islam.firebasestorage.app',
    measurementId: 'G-SLHGQ3Z195',
  );

}